version: '3.2'

services:
  cfssl:
    image: cfssl/cfssl
    restart: 'no'
    entrypoint: /bin/bash
    command:
      - /etc/sslconf/gen_crt.sh
    volumes:
      - ./config/cfssl:/etc/sslconf:ro
      - ./data/ssl/internal:/etc/ssl:rw
      - ./data/ssl/public:/etc/tmp_ssl:rw

  database:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - database:/var/lib/postgresql/data
      - ./one_time_config/postgresql.init:/docker-entrypoint-initdb.d:ro
    env_file: 
      - env/postgre.env
      - env/authentik_postgres.env
      - env/hass_postgres.env
    networks:
      - backbone
  
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./config/nginx:/etc/nginx/conf.d:ro
      - ./data/ssl/internal/ca_intermediate/intermediate_ca_fullchain.pem:/etc/ca/intermediate_ca_fullchain.pem:ro
      - ./data/ssl/public:/etc/ssl/:ro
    depends_on:
      - authentik-server
    networks:
      - auth
      - ingress
      - hass
      - mgnmt
  
  redis:
    image: redis
    restart: unless-stopped
    entrypoint: /bin/bash
    command: /init/init.sh
    env_file:
      - env/authentik_redis.env
    networks:
      - auth
    volumes:
      - ./one_time_config/redis.init/:/init:ro

  authentik-server:
    image: ghcr.io/goauthentik/server:2022.4.1
    restart: unless-stopped
    depends_on:
      - cfssl
      - database
      - redis
      - geoipupdate
    entrypoint: /bin/sh
    command: /init/init.sh
    env_file:
      - env/authentik.env
      - env/authentik_postgres.env
      - env/authentik_redis.env
    volumes:
      - ./one_time_config/authentik.init/:/init
      - ./data/authentik/media:/media
      - ./data/authentik/custom-templates:/templates
      - geoip:/geoip
    networks:
      - backbone
      - auth
    ports:
      - 9000:9443
  
  authentik-worker:
    image: ghcr.io/goauthentik/server:2022.4.1
    restart: unless-stopped
    command: worker
    depends_on:
      - cfssl
      - database
      - redis
      - geoipupdate
    env_file:
      - env/authentik.env
      - env/authentik_postgres.env
      - env/authentik_redis.env
    user: root
    volumes:
      - ./data/authentik/media:/media
      - ./data/authentik/custom-templates:/templates
      - ./data/ssl/internal/certs/authentik-server:/certs/authentik-server
      - /var/run/docker.sock:/var/run/docker.sock
      - geoip:/geoip
    networks:
      - backbone
      - auth
  
  geoipupdate:
    image: "maxmindinc/geoipupdate:latest"
    volumes:
      - "geoip:/usr/share/GeoIP"
    env_file:
      - env/geoip.env
    networks:
      - auth

volumes:
  database:
    driver: local
  geoip:
    driver: local

networks:
  backbone:
    ipam:
      config:
        - subnet: 172.0.0.0/16
  auth:
    ipam:
      config:
        - subnet: 172.1.0.0/16
  ingress:
    ipam:
      config:
        - subnet: 172.254.0.0/16
  hass:
    ipam:
      config:
        - subnet: 172.2.0.0/16
  mgnmt:
    ipam:
      config:
        - subnet: 172.253.0.0/16