global:
  scrape_interval:     15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'postgresql'
    static_configs:
      - targets: ['prometheus-postgres-exporter:9187']
  - job_name: 'nginx'
    static_configs:
      - targets: ['prometheus-nginx-exporter:9113']
  - job_name: 'authentik'
    static_configs:
      - targets: ['authentik-server:9300']
  - job_name: 'docker'
    static_configs:
      - targets: ['172.253.0.1:9323']
  - job_name: 'system'
    static_configs:
      - targets: ['172.253.0.1:9100']
  - job_name: 'certbot'
    static_configs:
      - targets: ['certbot:8556']