name: Home
latitude: 32.87336
longitude: 117.22743
elevation: 430
unit_system: metric
currency: USD
time_zone: "America/Los_Angeles"
external_url: !env_var HASS_URL
allowlist_external_dirs: []
allowlist_external_urls: []
media_dirs:
  media: "/media"
legacy_templates: false

