api_version: 2

ssl: true
verify_ssl: false

host: influxdb
port: 8086
token: !env_var INFLUX_TOKEN
organization: !env_var INFLUX_ORG_NAME
bucket: !env_var INFLUX_BUCKET
tags:
    source: HA
tags_attributes:
    - friendly_name