
default_config:

tts:
  - platform: google_translate

automation: !include config/automations.yaml
script: !include config/scripts.yaml
scene: !include config/scenes.yaml
http: !include config/http.yaml
recorder: !include config/recorder.yaml
homeassistant: !include config/homeassistant.yaml
auth_header:
  username_header: X-authentik-username

panel_iframe: !include config/iframes.yaml

logger:
    default: info